const planetFacts = {
  Mercury: 'One Mercury year is equal to only 88 Earth days. Mercury is only slightly larger than the Earth’s moon. Mercury travels around the sun more quickly than any of the other planets in the solar system. The core at Mercury’s center is mostly made up of iron and takes up about 75% of the planet’s radius.',
  Venus: 'It is the only planet named after a female and it’s thought that it was because it is the brightest planet. Venus has over 1,600 volcanoes, the most of any planet within the solar system. It takes Venus 243 Earth days to make one complete rotation. If you could stand on the surface of Venus, the air pressure would be so extreme, that it would be like being under Earth’s ocean half a mile down.',
  Earth: 'Even though you might think you are standing still, the Earth is turning. The speed at the equator is around 1,000 mph. Earth is constantly recycling its material through tectonic movement which drags surface rocks back down below the surface to become magma and then is spewed back out from volcanoes. The hottest recorded temperature location on the Earth is in El Azizia, Libya with temperatures hitting 136 degrees F/57.8 degrees C in 1922.',
  Mars: 'There have been 40 missions to Mars, but only 18 of the missions were successful. The dust storms on Mars are so large that they are considered to be the biggest in the solar system. Earth and Mars are the only to planets in the solar system with polar ice caps. Mars does have seasons but they are twice as long as the seasons on Earth due to Mars’ axis tilt.',
  Jupiter: 'Jupiter holds the title of being the solar system’s fourth brightest object. As asteroids and comets have impacted Jupiter they kick up dust particles that have created a very faint ring around Jupiter. The discovery of Jupiter’s 4 moons by Galileo was the first proof that the Earth was not the center of the universe and evidence that planets orbited the sun. We can only see five planets with the naked eye and Jupiter is one of them.',
  Saturn: 'There are only five planets that can be seen from Earth with the naked eye, Saturn is one of them. Most planets are somewhat spherical in shape, but Saturn is flatter; in fact it’s the flattest of any planet in the solar system. Saturn is the one planet that has the most extensive system of rings in the entire solar system. Earth’s magnetic field is just a little stronger than that of Saturn.',
  Uranus: 'Uranus has the coldest temperatures of all of the planets, hitting as low as -224 degrees C. Uranus has a tilted axis and it’s thought that a collision with another large celestial object was the cause of it. Uranus may be one of the “gas giants” but it is also the lightest in mass. The moons of Uranus are named after characters created by William Shakespeare and Alexander Pope.',
  Neptune: 'Neptune’s rings are so faint that prior to the Voyager 2 spacecraft mission, the rings weren’t thought to be complete. Neptune has the faintest rings of all of the gas giants. Even though Neptune is a gas giant it has the second largest gravity of all of the solar system planets. Neptune has a Great Dark Spot that is the size of our Earth and a Small Dark Spot that is almost the size of our moon.',
  Pluto: 'Pluto was named by an 11-year old girl from England. Pluto is considered to be the largest dwarf planet discovered so far. There was at one time quite a bit of controversy as to whether Eris or Pluto was the largest dwarf planet. Pluto is thought to be made up of around one third water which is in the form of ice. Pluto sometimes has an atmosphere and then sometimes not.',
  Moon: 'The diameter of the moon is the same distance in miles from Phoenix, AZ to New York City. The moon is covered in craters from impacts from meteors and comets. The lack of an atmosphere on the moon gives scientists an in-depth detailed view of the history of impacts on the surface. The moon also doesn’t have any tectonic activity or weather that would cover or resurface the craters.'
};

module.exports = planetFacts;